### PR TITLE
Make enemies face the correct way

### PR DESCRIPTION
**Pull request by aikios**
I think this should solve the problem, see individual commits for details

### CODE REVIEW

**Comment by AdamSpannbauer** [comment]
I'm not at a computer rn. Have you run demo.py and confirmed that the updates work as expected?

**Comment by aikios** [comment]
No, I'm not sure how to set up a testing environment.

**Comment by AdamSpannbauer** [comment]
Assuming your working directory is set to this repo, you can install all the [requirements](https://github.com/TriCot-Game-Studio/bullets/blob/main/requirements.txt) by running:

```
pip install -r requirements.txt
```

<sub>(as of now `pygame` is the only req, but good to know about how `requirements.txt`s work)</sub>

From there we've been testing by running `demo.py`.  Let me know if you run into trouble in getting this up and running and I can help out.  Actually running the code will make dev work so much easier/rewarding and it will make reviewing your code so much easier since you will have tested out what's working.

**Review by AdamSpannbauer — APPROVED** [review]

**Comment by AdamSpannbauer** [comment]
LGTM

**Pull request merged**
